services:
  - type: static
    name: portfolio
    rootDir: client
    buildCommand: npm ci && npm run build
    publishDir: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 